### ISSUE TITLE
non-template value passed to Polymer's html function

### ISSUE THREAD

**Issue by sergicontre** [kcmr/code-sample#11]
When references to JS literals are included, it is not able to escape expressions of the type
${example}

Example:

```
 export class Example extends ExampleBase {
                static get template() {
                  return html'
                        <p>${super.template}</p>
                    ';
                }
            }
```

Error in web console:

Uncaught Error: non-template value passed to Polymer's html function: undefined
    at htmlValue (html-tag.js:63)
    at template.innerHTML.values.reduce (html-tag.js:106)
    at Array.reduce (<anonymous>)
    at html (html-tag.js:106)

**Comment by kcmr** [comment]
I think that this case can only be handled from the component that includes `<code-sample>` because the expression is found in its template. The `connectedCallback()` method of `<code-sample>` does not even get called. I suppose that you have `<code-sample>` in the template of another component, is that the case?

Is a valid option for you to escape the expression in your template? (`\${super.template}`)

**Comment by sergicontre** [comment]
Yes, that is the case. When in the code to be formatted includes expressions of that type, which the Web Component itself tries to parse, we get that problem.

It may be an option that you comment. You just need a way to indicate in the code to format that it can be escaped :)
